apiVersion : apps/v1
kind: Deployment
metadata:
  name: "demoaks4-ad06"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "demoaks4-ad06"
  template:
    metadata:
      labels:
        app: "demoaks4-ad06"
    spec:
      containers:
        - name: "demoaks4-ad06"
          image: "registrydemoaks.azurecr.io/demoaks4"
          ports:
          - containerPort: 80