apiVersion: v1
kind: Service
metadata:
    name: "test123-18fe"
    labels:
        app: "test123-18fe"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "test123-18fe"