on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: testlabaks21.azurecr.io
        username: ${{ secrets.acr_testlabaks21_username }}
        password: ${{ secrets.acr_testlabaks21_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t testlabaks21.azurecr.io/testlabaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push testlabaks21.azurecr.io/testlabaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_testlabaks_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep testlabaks8d37 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace testlabaks8d37`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testlabaks8d37
        container-registry-url: testlabaks21.azurecr.io
        container-registry-username: ${{ secrets.acr_testlabaks21_username }}
        container-registry-password: ${{ secrets.acr_testlabaks21_password }}
        secret-name: testlabaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: testlabaks8d37
        manifests: |
          manifests/deployment-7.yml
          manifests/service-7.yml
        images: |
          testlabaks21.azurecr.io/testlabaks:${{ github.sha }}
        imagepullsecrets: |
          testlabaksdockerauth
