on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: registrydemoaks.azurecr.io
        username: ${{ secrets.acr_registrydemoaks_username }}
        password: ${{ secrets.acr_registrydemoaks_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t registrydemoaks.azurecr.io/demoaks4:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push registrydemoaks.azurecr.io/demoaks4:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         client-id: "5e91c637-7b6e-41af-a21b-a1e0490fbb1c"
         tenant-id: "0f542e4f-0469-4998-8325-8f33ecd14878"
         subscription-id: "3499fb03-2a71-4296-ba87-6e140b0540f6" 
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep demoaks4a4dd | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace demoaks4a4dd`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: demoaks4a4dd
        container-registry-url: registrydemoaks.azurecr.io
        container-registry-username: ${{ secrets.acr_registrydemoaks_username }}
        container-registry-password: ${{ secrets.acr_registrydemoaks_password }}
        secret-name: demoaks4dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: demoaks4a4dd
        manifests: |    
          ./strapi-service.yaml
          ./strapi-deployment.yaml
          ./strapi-service.yaml
          ./postgresdb-claim0-persistentvolumeclaim.yaml

        images: |
          registrydemoaks.azurecr.io/demoaks4:${{ github.sha }}
        imagepullsecrets: |
          demoaks4dockerauth
