on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrdemo1231.azurecr.io
        username: ${{ secrets.acr_acrdemo1231_username }}
        password: ${{ secrets.acr_acrdemo1231_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrdemo1231.azurecr.io/test123:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrdemo1231.azurecr.io/test123:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_test123_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep test12395f8 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace test12395f8`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: test12395f8
        container-registry-url: acrdemo1231.azurecr.io
        container-registry-username: ${{ secrets.acr_acrdemo1231_username }}
        container-registry-password: ${{ secrets.acr_acrdemo1231_password }}
        secret-name: test123dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: test12395f8
        manifests: |
          manifests/deployment-6.yml
          manifests/service-6.yml
        images: |
          acrdemo1231.azurecr.io/test123:${{ github.sha }}
        imagepullsecrets: |
          test123dockerauth
